### ISSUE TITLE
Using on Vue (Quasar Framework)

### ISSUE THREAD

**Issue by itsalb3rt** [mathiasvr/tiny-timer#11]
For using this in Quasar i need using explicit import;

```javascript
import Timer from 'tiny-timer/dist/tiny-timer.js'
```

**Comment by mathiasvr** [comment]
Hi, sorry for the long response time.
I have just updated the module to fix an issue with webpack, maybe it solves your issue too?

**Comment by itsalb3rt** [comment]
I think if. I will be pending. Thank you!

**Comment by itsalb3rt** [comment]
> Hi, sorry for the long response time.
> I have just updated the module to fix an issue with webpack, maybe it solves your issue too?

Now work perfect with Quasar! thanks!
