### ISSUE TITLE
Using with Ant Design Pro (based on React)

### ISSUE THREAD

**Issue by Dragon201701** [mathiasvr/tiny-timer#12]
./node_modules/tiny-timer/dist/tiny-timer.mjs 122:2-14
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)

**Comment by mathiasvr** [comment]
Hi, I think this was a problem with webpack and .mjs files.
I have just updated the module to v1.5.0, can you try the new version and let me know if that solves your issue?

**Comment by Dragon201701** [comment]
I run into issue says 
Unhandled Rejection (TypeError): Timer is not a constructor
Module../src/pages/EmptyPage/TableBasic/index.tsx
./src/pages/EmptyPage/TableBasic/index.tsx:107
  104 |     )
  105 |   }
  106 | ]; */
> 107 | const timer = new Timer({interval: 3000, stopwatch: false});
  108 | 
  109 | 
  110 | var dataSource;
View compiled
__webpack_require__
./webpack/bootstrap:773
  770 | };
  771 | 
  772 | // Execute the module function
> 773 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  774 | 
  775 | // Flag the module as loaded
  776 | module.l = true;
View compiled
fn
./webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
      | ^  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
Module../src/pages/EmptyPage/index.tsx
http://localhost:8001/p__EmptyPage.js:463:69
__webpack_require__
./webpack/bootstrap:773
  770 | };
  771 | 
  772 | // Execute the module function
> 773 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  774 | 
  775 | // Flag the module as loaded
  776 | module.l = true;
View compiled
fn
./webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
      | ^  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

I am using this inside a Ant Design Pro (React) Component inside the function: componentDidMount()

const Timer = require('tiny-timer')  
const timer = new Timer({interval: 3000, stopwatch: false});  
const dataSource = [];  
class VideoResult extends React.Component{  
  constructor(props) {  
    super(props);  
    // Don't call this.setState() here!  
    this.state = { data: dataSource };  
    //this.handleClick = this.handleClick.bind(this);  
  }  
  componentDidMount(){  
timer.on('tick', (ms) =>{  
      console.log("Fetch result...")  
      request('http://localhost:8081/api/result/').then(data=>{  
        //console.log(data);  
        dataSource.push(data);  
        //console.log(dataSource);  
        this.setState({  
          data: dataSource   
        })  
      })  
    })    
    timer.start();    
  }    
componentWillUnmount(){    
    timer.stop();    
  }

**Comment by mathiasvr** [comment]
Hm, can you see what `Timer` is if not a constructor?
Maybe you need to use `import Timer from 'tiny-timer'` instead of `require()`.

**Comment by Dragon201701** [comment]
I change to import TImer from 'tiny-timer' and works.
