### ISSUE TITLE
Request: add a changelog

### ISSUE THREAD

**Issue by codekiln** [mathiasvr/tiny-timer#5]
A colleague of mine used this npm package a while back, and now I'd like to update it. Without a changelog, it makes it harder to evaluate how risky the update is. Will you make a changelog?

**Comment by mathiasvr** [comment]
Hi, yes I agree this is a good idea, I will try to add one in the future.

For what it's worth the source code and API of this package has not changed much since it was first released, with the only major change being that it is now transpiled from ES6.
