### ISSUE TITLE
How to import into Angular project

### ISSUE THREAD

**Issue by JoeShields-IHC** [mathiasvr/tiny-timer#9]
Hi Im getting the following error when trying import into my angular project after importing.

import { Timer }  from 'tiny-timer';
/node_modules/tiny-timer/dist/tiny-timer"' has no exported member 'Timer'

Any ideas?
Thanks

**Comment by mathiasvr** [comment]
The module is using `default export`, so you have to import without the curly braces:
```js
import Timer from 'tiny-timer';
```

**Comment by JoeShields-IHC** [comment]
Cheers for the quick reply. that has fixed the import issue, however when  trying instatiate a basic Timer and compiling getting the following error:

[ng] Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)

Thoughts?

**Comment by mathiasvr** [comment]
Oh right, it depends on the nodejs EventEmitter, so it’s not currently directly compatible with the browser. You can however use webpack or similar to bundle it.

**Comment by gasolin** [comment]
@mathiasvr FYI I can use tiny-timer in react native by use `eventemitter2` module instead of node 'event'.

**Comment by mathiasvr** [comment]
Closing this as I think it is mostly solved now.
@gasolin Nice, I think removing the node event dependency is a good idea since it is the root of most issues with this module.
